name: CI - Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Python lint/test stage ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # --- Docker build/push stage ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            abdullahhamada7/flask-k8s:latest
            abdullahhamada7/flask-k8s:${{ github.sha }}

      # --- Manifest update stage
      - name: Install kubectl
        run: |
          curl -sSL "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Update Kubernetes manifest
        run: |
          kubectl set image -f k8s/deploy.yml \
            deployment/myapp-deploy myapp=abdullahhamada7/flask-k8s:${{ github.sha }} \
            --local -o yaml > k8s/deploy.yml.new
          mv k8s/deploy.yml.new k8s/deploy.yml

      - name: Commit manifest changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deploy.yml
          
          if git diff --staged --quiet; then
            echo "No manifest changes to commit."
          else
            git commit -m "Update deployment image to ${{ github.sha }} [skip ci]"
            git push
          fi
