name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            abdullahhamada7/flask-k8s:latest
            abdullahhamada7/flask-k8s:${{ github.sha }}

      - name: Update Manifest File
        run: |
          kubectl set image deployment/myapp-deploy myapp=abdullahhamada7/flask-k8s:${{ github.sha }} --local -o yaml > k8s/deploy.yml.new
          mv k8s/deploy.yml.new k8s/deploy.yml

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1.0.1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          manifests: |
            ./k8s/deploy.yml
            ./k8s/svc.yml

      - name: Verify Deployment
        run: |
          echo "Waiting for pods to be ready..."
          kubectl wait --for=condition=Ready pod -l app=myapp --timeout=120s
          echo "Pods are ready!"
      
      - name: Commit Updated Manifest
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add k8s/deploy.yml
          
          if git diff --staged --quiet; then
            echo "No changes to the manifest to commit."
          else
            # Add [skip ci] to the commit message to prevent an infinite loop
            git commit -m "Update deployment image to ${{ github.sha }} [skip ci]"
            git push
          fi

